server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java9TahminYonetim
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}

rabbitmq:
  tahminExchange: tahminExchange
  skorGuncelleQueue: skorGuncelleQueue
  skorGuncelleBindingKey: skorGuncelleBindingKey